Repository Afterlight-3149/afterlight-3149, pull requests merged in 2022-12, with the labels that each got.

#1 Update the game's branding to AL3149.
  Resources/Textures/Logo/al3149.png
  Resources/Textures/Logo/alicon/icon-128x128.png
  Resources/Textures/Logo/alicon/icon-16x16.png
  Resources/Textures/Logo/alicon/icon-24x24.png
  Resources/Textures/Logo/alicon/icon-256x256.png
  Resources/Textures/Logo/alicon/icon-32x32.png
  Resources/Textures/Logo/alicon/icon-48x48.png
  Resources/Textures/Logo/alicon/icon-64x64.png
  Resources/manifest.yml
Labels: No C#

#2 forge shuttle
  Resources/Maps/_Afterlight/Vessels/forge.yml
  Resources/Prototypes/_Afterlight/Maps/Vessels/forge.yml
Labels: No C#, Status: Needs Review

#3 Port Outer Rim latejoin.
  Content.Client/Lobby/LobbyState.cs
  Content.Client/_Afterlight/GameMapPrototype.cs
  Content.Client/_Afterlight/Latejoin/NewVesselGui.xaml
  Content.Client/_Afterlight/Latejoin/NewVesselGui.xaml.cs
  Content.Client/_Afterlight/Latejoin/OuterRimLateJoinGui.xaml
  Content.Client/_Afterlight/Latejoin/OuterRimLateJoinGui.xaml.cs
  Content.Client/_Afterlight/Latejoin/OuterRimLateJoinJobButton.xaml
  Content.Client/_Afterlight/Latejoin/OuterRimLateJoinJobButton.xaml.cs
  Content.Client/_Afterlight/Latejoin/VesselListControl.xaml
  Content.Client/_Afterlight/Latejoin/VesselListControl.xaml.cs
  Content.Server/_Afterlight/Worldgen/Components/ShipSpawningComponent.cs
  Content.Server/_Afterlight/Worldgen/Systems/ShipSpawningSystem.cs
  Content.Shared/CCVar/CCVars.cs
  Content.Shared/_Afterlight/Worldgen/ShipSpawningEvent.cs
  Resources/Prototypes/_Afterlight/Maps/Vessels/forge.yml
  Resources/Prototypes/_Afterlight/Maps/cfg.yml
  Resources/Prototypes/_Afterlight/World/config.yml
Labels: Changes: UI

#5 fixe
  Content.Client/_Afterlight/Latejoin/OuterRimLateJoinGui.xaml
  Content.Client/_Afterlight/Latejoin/OuterRimLateJoinGui.xaml.cs
  Content.Client/_Afterlight/Spawning/ShipSpawningSystem.cs
  Content.IntegrationTests/PoolManager.cs
  Content.Server/Maps/GameMapPrototype.cs
  Content.Server/Station/Systems/StationJobsSystem.Roundstart.cs
  Content.Server/_Afterlight/AfterlightCVars.cs
  Content.Server/_Afterlight/Worldgen/Systems/ShipSpawningSystem.cs
  Content.Server/_Citadel/Worldgen/WorldgenCVars.cs
  Content.Shared.Database/LogType.cs
  Content.Shared/_Afterlight/Worldgen/ShipSpawningEvent.cs
Labels: Changes: UI

#8 Port and touch up outer rim generators.
  Content.Client/_Afterlight/Generator/GeneratorWindow.xaml
  Content.Client/_Afterlight/Generator/GeneratorWindow.xaml.cs
  Content.Client/_Afterlight/Generator/SolidFuelGeneratorBoundUserInterface.cs
  Content.Server/_Afterlight/Generator/ChemicalFuelGeneratorAdapterComponent.cs
  Content.Server/_Afterlight/Generator/ChemicalFuelGeneratorDirectSourceComponent.cs
  Content.Server/_Afterlight/Generator/GasPowerProviderComponent.cs
  Content.Server/_Afterlight/Generator/GasPowerProviderSystem.cs
  Content.Server/_Afterlight/Generator/GeneratorSystem.cs
  Content.Server/_Afterlight/Generator/SolidFuelGeneratorAdapterComponent.cs
  Content.Shared/_Afterlight/Generator/FuelGeneratorComponent.cs
  Content.Shared/_Afterlight/Generator/SharedGeneratorSystem.cs
  Resources/Prototypes/Entities/Structures/Power/Generation/generators.yml
Labels: Changes: UI

#9 Fix several issues.
  Content.Client/_Afterlight/Generator/GeneratorWindow.xaml.cs
  Content.Server/_Afterlight/Generator/GeneratorSystem.cs
  Content.Shared/_Afterlight/Generator/FuelGeneratorComponent.cs
  Resources/Maps/_Afterlight/Vessels/forge.yml
  Resources/Prototypes/Catalog/VendingMachines/Inventories/salvage.yml
  Resources/Prototypes/_Afterlight/Entities/World/Debris/wrecks.yml
Labels: Changes: UI

#17 respawning.
  Content.Client/UserInterface/Systems/Ghost/GhostUIController.cs
  Content.Client/UserInterface/Systems/Ghost/Widgets/GhostGui.xaml
  Content.Client/UserInterface/Systems/Ghost/Widgets/GhostGui.xaml.cs
  Content.Server/Ghost/Components/GhostComponent.cs
  Content.Server/Ghost/GhostSystem.cs
  Content.Server/_Afterlight/Commands/GhostRespawnCommand.cs
  Content.Shared/Ghost/SharedGhostComponent.cs
  Content.Shared/_Afterlight/AfterlightCVarsShared.cs
Labels: Changes: UI

#20 Amalgam Ship
  Resources/Maps/_Afterlight/Vessels/amalgam.yml
  Resources/Prototypes/_Afterlight/Maps/Vessels/amalgam.yml
Labels: No C#

#19 Fiesta
  Resources/Maps/_Afterlight/Vessels/fiesta.yml
  Resources/Prototypes/_Afterlight/Maps/Vessels/fiesta.yml
Labels: No C#

#22 Fix generators reporting a target power of 0.
  Content.Client/_Afterlight/Generator/GeneratorWindow.xaml.cs
Labels: Changes: UI

#23 Amalgam Tweaks
  Resources/Maps/_Afterlight/Vessels/amalgam.yml
Labels: No C#

#25 Remove the current map display and hide full vessels.
  Content.Client/_Afterlight/Latejoin/VesselListControl.xaml.cs
  Content.Server/GameTicking/GameTicker.Lobby.cs
Labels: Changes: UI

#27 ISV Chip
  Resources/Maps/_Afterlight/Vessels/chip.yml
  Resources/Prototypes/_Afterlight/Maps/Vessels/chip.yml
Labels: No C#

#28 Reise
  Resources/Maps/_Afterlight/Vessels/reise.yml
  Resources/Prototypes/_Afterlight/Maps/Vessels/reise.yml
Labels: No C#

#26 The JuneBug
  Resources/Maps/_Afterlight/Vessels/junebug.yml
  Resources/Prototypes/_Afterlight/Maps/Vessels/junebug.yml
Labels: No C#

#32 Remove The Handheld Radio From The Salvage Vendor
  Resources/Prototypes/Catalog/VendingMachines/Inventories/salvage.yml
Labels: No C#

#31 Reduced Head Locker Fills
  Resources/Prototypes/Catalog/Fills/Lockers/heads.yml
Labels: No C#
